### ISSUE TITLE
ProductFiles - consider breaking out into a separate module, suggesting via composer

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-products#29]
This is used less and less lately, makes sense for this to be an add-on module to silverstripe-products, used on a per-project basis.

Would likely require a new major version of silverstripe-products

**Comment by muskie9** [comment]
I could see this split out. It's definitely useful when it's needed, but bloat when it's not. Knowing there are use cases where products are fed from product databases like Salsify can also add a level of complexity to use the built in Product Files, or customize the Product record (or its decedents) to handle any files differently.

If we do split it out, I'd imagine we'd need the following:
- [ ] New major version (as noted above)
- [ ] Migration path for base file classes
- [ ] Upgrade tips for cases where the Product Files were subclassed

**Comment by jsirish** [comment]
I think #'s 2 and 3 would be necessary if we change the namespace. Ideally we would not change the $table_name, then a simple `legacy.yml` would update the namespaces.

If done correctly, including the new module in an existing project would not break anything.

The subclassed Product Files would definitely require some documentation on a namespace change, re: updating `use` statements.

Am I thinking about this correctly? Thanks for the feedback, I'll likely look at this in the next couple weeks.
